"""Base strategy interface and signal model."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from market_data.models import MarketTick


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    id: str = field(default_factory=lambda: str(uuid4()))
    symbol: str = ""
    strategy_name: str = ""
    action: str = "buy"  # buy | sell
    order_type: str = "market"  # market | limit
    quantity: int = 0
    price: float | None = None
    trigger_price: float = 0.0
    confidence: float = 1.0
    conditions_met: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "symbol": self.symbol,
            "strategy_name": self.strategy_name,
            "action": self.action,
            "order_type": self.order_type,
            "quantity": self.quantity,
            "price": self.price,
            "trigger_price": self.trigger_price,
            "confidence": self.confidence,
            "conditions_met": self.conditions_met,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    name: str = "base"
    description: str = ""

    def __init__(self, config: dict[str, Any]):
        self.config = config
        self.parameters = config.get("parameters", {})
        self.enabled = config.get("enabled", True)

    @abstractmethod
    async def evaluate(self, tick: MarketTick) -> Signal | None:
        """Evaluate market tick and return signal if conditions met."""
        ...

    def _resolve_param(self, value: Any) -> Any:
        """Resolve ${param_name} template references."""
        if isinstance(value, str) and value.startswith("${") and value.endswith("}"):
            param_name = value[2:-1]
            return self.parameters.get(param_name, value)
        return value

    def _evaluate_condition(self, tick: MarketTick, condition: dict) -> tuple[bool, dict]:
        """Evaluate a single condition against market tick."""
        field_name = condition["field"]
        operator = condition["operator"]

        # Get tick field value
        tick_value = getattr(tick, field_name, None)
        if tick_value is None and field_name in ("bid_quantity", "ask_quantity"):
            tick_value = tick.total_bid_quantity if field_name == "bid_quantity" else tick.total_ask_quantity
        if tick_value is None:
            tick_value = tick.to_dict().get(field_name)

        # Get comparison value
        if "reference" in condition:
            compare_value = getattr(tick, condition["reference"], None)
            if compare_value is None:
                compare_value = tick.to_dict().get(condition["reference"])
        elif "value" in condition:
            compare_value = self._resolve_param(condition["value"])
        else:
            return False, {"error": "no comparison value"}

        # Apply operator
        ops = {
            "gte": lambda a, b: a >= b,
            "lte": lambda a, b: a <= b,
            "gt": lambda a, b: a > b,
            "lt": lambda a, b: a < b,
            "eq": lambda a, b: a == b,
            "ne": lambda a, b: a != b,
        }
        op_func = ops.get(operator)
        if not op_func:
            return False, {"error": f"unknown operator: {operator}"}

        try:
            result = op_func(float(tick_value), float(compare_value))
        except (TypeError, ValueError):
            result = False

        return result, {
            "field": field_name,
            "operator": operator,
            "tick_value": tick_value,
            "compare_value": compare_value,
            "result": result,
        }


class StrategyRegistry:
    """Registry of available strategy implementations."""

    _strategies: dict[str, type[BaseStrategy]] = {}

    @classmethod
    def register(cls, name: str, strategy_class: type[BaseStrategy]) -> None:
        cls._strategies[name] = strategy_class

    @classmethod
    def create(cls, name: str, config: dict) -> BaseStrategy:
        strategy_class = cls._strategies.get(name)
        if not strategy_class:
            raise ValueError(f"Unknown strategy: {name}")
        return strategy_class(config)

    @classmethod
    def available(cls) -> list[str]:
        return list(cls._strategies.keys())
